version: "3.8"

##############################################################################
#
# services
# - spark (master)
# - spark-worker
#
##############################################################################
services:

  ####################
  # spark (master)
  ####################
  spark:
    # image: bitnami/spark:3.3.1
    image: apache/spark-py:v3.3.1
    hostname: spark
    container_name: spark
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no      
    ports:
      - '8080:8080'
      - '7077:7077'
    networks:
      - backend
    volumes:
      - ./apps:/apps
      - type: bind
        source: ./data
        target: /opt/spark/data
    restart: always

  ####################
  # spark-worker
  ####################
  spark-worker:
    # image: bitnami/spark:3.3.1
    image: apache/spark-py:v3.3.1
    # container_name: spark-woker
    networks:
      - backend
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - type: bind
        source: ./data
        target: /opt/spark/data
    restart: always

################################################################################
#
# networks
# - backend
#
################################################################################
networks:
  backend:
    name: backend
    external: true