apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose-kafka.yml
    kompose.version: 1.27.0 (b0ed6a2c9)
  creationTimestamp: null
  labels:
    io.kompose.service: kafkacat
  name: kafkacat
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafkacat
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose-kafka.yml
        kompose.version: 1.27.0 (b0ed6a2c9)
      creationTimestamp: null
      labels:
        io.kompose.network/backend: "true"
        io.kompose.service: kafkacat
    spec:
      containers:
        - command:
            - /bin/sh
            - -c
            - "apk add jq; \nwhile [ 1 -eq 1 ];do sleep 60;done\n"
          image: edenhill/kafkacat:1.6.0
          name: kafkacat
          resources: {}
      restartPolicy: Always
status: {}
