apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose-kafka.yml
    kompose.version: 1.27.0 (b0ed6a2c9)
  creationTimestamp: null
  labels:
    io.kompose.service: ksqldb-cli
  name: ksqldb-cli
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ksqldb-cli
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose-kafka.yml
        kompose.version: 1.27.0 (b0ed6a2c9)
      creationTimestamp: null
      labels:
        io.kompose.network/backend: "true"
        io.kompose.service: ksqldb-cli
    spec:
      containers:
        - command:
            - /bin/sh
          image: confluentinc/cp-ksqldb-cli:7.3.1
          name: ksqldb-cli
          resources: {}
          tty: true
      restartPolicy: Always
status: {}
