{
 "title": "Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "First 10 rows",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT * FROM topic_dailyc19 LIMIT 10;"
    }
   ]
  },
  {
   "title": "Washington",
   "type": "bargauge",
   "gridPos": { "h": 28, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(cases) AS \"cases\", date FROM topic_dailyc19 WHERE state = 'Washington' GROUP BY date ORDER BY date ASC LIMIT 100 "
    }
   ]
  },
  {
   "title": "On March 31, 2020",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT \n  state,\n  SUM(cases) AS cases, \n  100 *SUM(cases) / (SELECT SUM(cases) FROM topic_dailyc19 WHERE date = '2020-03-31') AS percent\nFROM topic_dailyc19\nWHERE date = '2020-03-31'\nGROUP BY state\nORDER BY percent DESC;\n"
    }
   ]
  },
  {
   "title": "On March 31, 2020",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "    SELECT\n        SUM(cases) AS cases,\n        state as metric\n    FROM topic_dailyc19\n    WHERE date = '2020-03-31'\n    GROUP BY state;\n"
    }
   ]
  }
 ]
}